/**
 * Swagger Petstore - OpenAPI 3.0
 * This is a sample Pet Store Server based on the OpenAPI 3.0 specification. You can find out more about Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach! You can now help us improve the API whether it's by making changes to the definition itself or to the code. That way, with time, we can improve the API in general, and expose some of the new features in OAS3.  _If you're looking for the Swagger 2.0/OAS 2.0 version of Petstore, then click [here](https://editor.swagger.io/?url=https://petstore.swagger.io/v2/swagger.yaml). Alternatively, you can load via the `Edit > Load Petstore OAS 2.0` menu option!_  Some useful links: - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore) - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
 *
 * The version of the OpenAPI document: 1.0.11
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PublicMatchesDto model module.
 * @module model/PublicMatchesDto
 * @version 1.0.11
 */
class PublicMatchesDto {
    /**
     * Constructs a new <code>PublicMatchesDto</code>.
     * @alias module:model/PublicMatchesDto
     */
    constructor() { 
        
        PublicMatchesDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PublicMatchesDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PublicMatchesDto} obj Optional instance to populate.
     * @return {module:model/PublicMatchesDto} The populated <code>PublicMatchesDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PublicMatchesDto();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('equipe1')) {
                obj['equipe1'] = ApiClient.convertToType(data['equipe1'], 'String');
            }
            if (data.hasOwnProperty('equipe2')) {
                obj['equipe2'] = ApiClient.convertToType(data['equipe2'], 'String');
            }
            if (data.hasOwnProperty('score')) {
                obj['score'] = ApiClient.convertToType(data['score'], 'String');
            }
            if (data.hasOwnProperty('termine')) {
                obj['termine'] = ApiClient.convertToType(data['termine'], 'Boolean');
            }
            if (data.hasOwnProperty('date_debut')) {
                obj['date_debut'] = ApiClient.convertToType(data['date_debut'], 'Number');
            }
            if (data.hasOwnProperty('photo')) {
                obj['photo'] = ApiClient.convertToType(data['photo'], 'String');
            }
            if (data.hasOwnProperty('lieu')) {
                obj['lieu'] = ApiClient.convertToType(data['lieu'], 'String');
            }
            if (data.hasOwnProperty('arbitre')) {
                obj['arbitre'] = ApiClient.convertToType(data['arbitre'], 'String');
            }
            if (data.hasOwnProperty('tournoi')) {
                obj['tournoi'] = ApiClient.convertToType(data['tournoi'], 'String');
            }
            if (data.hasOwnProperty('stat')) {
                obj['stat'] = ApiClient.convertToType(data['stat'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PublicMatchesDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PublicMatchesDto</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['equipe1'] && !(typeof data['equipe1'] === 'string' || data['equipe1'] instanceof String)) {
            throw new Error("Expected the field `equipe1` to be a primitive type in the JSON string but got " + data['equipe1']);
        }
        // ensure the json data is a string
        if (data['equipe2'] && !(typeof data['equipe2'] === 'string' || data['equipe2'] instanceof String)) {
            throw new Error("Expected the field `equipe2` to be a primitive type in the JSON string but got " + data['equipe2']);
        }
        // ensure the json data is a string
        if (data['score'] && !(typeof data['score'] === 'string' || data['score'] instanceof String)) {
            throw new Error("Expected the field `score` to be a primitive type in the JSON string but got " + data['score']);
        }
        // ensure the json data is a string
        if (data['photo'] && !(typeof data['photo'] === 'string' || data['photo'] instanceof String)) {
            throw new Error("Expected the field `photo` to be a primitive type in the JSON string but got " + data['photo']);
        }
        // ensure the json data is a string
        if (data['lieu'] && !(typeof data['lieu'] === 'string' || data['lieu'] instanceof String)) {
            throw new Error("Expected the field `lieu` to be a primitive type in the JSON string but got " + data['lieu']);
        }
        // ensure the json data is a string
        if (data['arbitre'] && !(typeof data['arbitre'] === 'string' || data['arbitre'] instanceof String)) {
            throw new Error("Expected the field `arbitre` to be a primitive type in the JSON string but got " + data['arbitre']);
        }
        // ensure the json data is a string
        if (data['tournoi'] && !(typeof data['tournoi'] === 'string' || data['tournoi'] instanceof String)) {
            throw new Error("Expected the field `tournoi` to be a primitive type in the JSON string but got " + data['tournoi']);
        }
        // ensure the json data is a string
        if (data['stat'] && !(typeof data['stat'] === 'string' || data['stat'] instanceof String)) {
            throw new Error("Expected the field `stat` to be a primitive type in the JSON string but got " + data['stat']);
        }

        return true;
    }

/**
     * Returns Identifiant unique du match
     * @return {String}
     */
    getId() {
        return this.id;
    }

    /**
     * Sets Identifiant unique du match
     * @param {String} id Identifiant unique du match
     */
    setId(id) {
        this['id'] = id;
    }
/**
     * @return {String}
     */
    getEquipe1() {
        return this.equipe1;
    }

    /**
     * @param {String} equipe1
     */
    setEquipe1(equipe1) {
        this['equipe1'] = equipe1;
    }
/**
     * @return {String}
     */
    getEquipe2() {
        return this.equipe2;
    }

    /**
     * @param {String} equipe2
     */
    setEquipe2(equipe2) {
        this['equipe2'] = equipe2;
    }
/**
     * Returns Score du match
     * @return {String}
     */
    getScore() {
        return this.score;
    }

    /**
     * Sets Score du match
     * @param {String} score Score du match
     */
    setScore(score) {
        this['score'] = score;
    }
/**
     * Returns Indique si le match est terminé
     * @return {Boolean}
     */
    getTermine() {
        return this.termine;
    }

    /**
     * Sets Indique si le match est terminé
     * @param {Boolean} termine Indique si le match est terminé
     */
    setTermine(termine) {
        this['termine'] = termine;
    }
/**
     * Returns Date de début du match
     * @return {Number}
     */
    getDateDebut() {
        return this.date_debut;
    }

    /**
     * Sets Date de début du match
     * @param {Number} dateDebut Date de début du match
     */
    setDateDebut(dateDebut) {
        this['date_debut'] = dateDebut;
    }
/**
     * Returns URL de la photo du match
     * @return {String}
     */
    getPhoto() {
        return this.photo;
    }

    /**
     * Sets URL de la photo du match
     * @param {String} photo URL de la photo du match
     */
    setPhoto(photo) {
        this['photo'] = photo;
    }
/**
     * Returns Lieu où se déroule le match
     * @return {String}
     */
    getLieu() {
        return this.lieu;
    }

    /**
     * Sets Lieu où se déroule le match
     * @param {String} lieu Lieu où se déroule le match
     */
    setLieu(lieu) {
        this['lieu'] = lieu;
    }
/**
     * Returns Nom de l'arbitre du match
     * @return {String}
     */
    getArbitre() {
        return this.arbitre;
    }

    /**
     * Sets Nom de l'arbitre du match
     * @param {String} arbitre Nom de l'arbitre du match
     */
    setArbitre(arbitre) {
        this['arbitre'] = arbitre;
    }
/**
     * @return {String}
     */
    getTournoi() {
        return this.tournoi;
    }

    /**
     * @param {String} tournoi
     */
    setTournoi(tournoi) {
        this['tournoi'] = tournoi;
    }
/**
     * @return {String}
     */
    getStat() {
        return this.stat;
    }

    /**
     * @param {String} stat
     */
    setStat(stat) {
        this['stat'] = stat;
    }

}



/**
 * Identifiant unique du match
 * @member {String} id
 */
PublicMatchesDto.prototype['id'] = undefined;

/**
 * @member {String} equipe1
 */
PublicMatchesDto.prototype['equipe1'] = undefined;

/**
 * @member {String} equipe2
 */
PublicMatchesDto.prototype['equipe2'] = undefined;

/**
 * Score du match
 * @member {String} score
 */
PublicMatchesDto.prototype['score'] = undefined;

/**
 * Indique si le match est terminé
 * @member {Boolean} termine
 */
PublicMatchesDto.prototype['termine'] = undefined;

/**
 * Date de début du match
 * @member {Number} date_debut
 */
PublicMatchesDto.prototype['date_debut'] = undefined;

/**
 * URL de la photo du match
 * @member {String} photo
 */
PublicMatchesDto.prototype['photo'] = undefined;

/**
 * Lieu où se déroule le match
 * @member {String} lieu
 */
PublicMatchesDto.prototype['lieu'] = undefined;

/**
 * Nom de l'arbitre du match
 * @member {String} arbitre
 */
PublicMatchesDto.prototype['arbitre'] = undefined;

/**
 * @member {String} tournoi
 */
PublicMatchesDto.prototype['tournoi'] = undefined;

/**
 * @member {String} stat
 */
PublicMatchesDto.prototype['stat'] = undefined;






export default PublicMatchesDto;

