/**
 * Swagger SportApplicatioh - OpenAPI 3.0
 * This is a sample Pet Store Server based on the OpenAPI 3.0 specification. You can find out more about Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach! You can now help us improve the API whether it's by making changes to the definition itself or to the code. That way, with time, we can improve the API in general, and expose some of the new features in OAS3.  _If you're looking for the Swagger 2.0/OAS 2.0 version of Petstore, then click [here](https://editor.swagger.io/?url=https://petstore.swagger.io/v2/swagger.yaml). Alternatively, you can load via the `Edit > Load Petstore OAS 2.0` menu option!_  Some useful links: - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore) - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
 *
 * The version of the OpenAPI document: 1.0.11
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CreateEquipeDto from '../model/CreateEquipeDto';
import EquipeDto from '../model/EquipeDto';
import UpdateEquipeDto from '../model/UpdateEquipeDto';

/**
* Equipe service.
* @module api/EquipeApi
* @version 1.0.11
*/
export default class EquipeApi {

    /**
    * Constructs a new EquipeApi. 
    * @alias module:api/EquipeApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * crée une nouvelle équipe
     * crée une nouvelle équipe
     * @param {module:model/CreateEquipeDto} createEquipeDto Create an new Team
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/EquipeDto} and HTTP response
     */
    createTeamWithHttpInfo(createEquipeDto) {
      let postBody = createEquipeDto;
      // verify the required parameter 'createEquipeDto' is set
      if (createEquipeDto === undefined || createEquipeDto === null) {
        throw new Error("Missing the required parameter 'createEquipeDto' when calling createTeam");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['sport_auth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = EquipeDto;
      return this.apiClient.callApi(
        '/Equipe', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * crée une nouvelle équipe
     * crée une nouvelle équipe
     * @param {module:model/CreateEquipeDto} createEquipeDto Create an new Team
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/EquipeDto}
     */
    createTeam(createEquipeDto) {
      return this.createTeamWithHttpInfo(createEquipeDto)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Supprimer une équipe avec son id
     * @param {Number} id The id that needs to be deleted
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    deleteTeamWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deleteTeam");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['sport_auth'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/Equipe/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Supprimer une équipe avec son id
     * @param {Number} id The id that needs to be deleted
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    deleteTeam(id) {
      return this.deleteTeamWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Récupérer une équipe par son id
     * @param {Number} id The id that needs to be deleted
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/EquipeDto} and HTTP response
     */
    getTeamByIdWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getTeamById");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['sport_auth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = EquipeDto;
      return this.apiClient.callApi(
        '/Equipe/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Récupérer une équipe par son id
     * @param {Number} id The id that needs to be deleted
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/EquipeDto}
     */
    getTeamById(id) {
      return this.getTeamByIdWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Récupérer toutes les équipes
     * @param {String} name The id that needs to be deleted
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/EquipeDto} and HTTP response
     */
    getTeamByNameWithHttpInfo(name) {
      let postBody = null;
      // verify the required parameter 'name' is set
      if (name === undefined || name === null) {
        throw new Error("Missing the required parameter 'name' when calling getTeamByName");
      }

      let pathParams = {
        'name': name
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['sport_auth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = EquipeDto;
      return this.apiClient.callApi(
        '/Equipe/name/{name}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Récupérer toutes les équipes
     * @param {String} name The id that needs to be deleted
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/EquipeDto}
     */
    getTeamByName(name) {
      return this.getTeamByNameWithHttpInfo(name)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * update une équipe existante
     * update une équipe existante
     * @param {Number} id The id that needs to be deleted
     * @param {module:model/UpdateEquipeDto} updateEquipeDto update an new Team
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/EquipeDto} and HTTP response
     */
    updateTeamAWithHttpInfo(id, updateEquipeDto) {
      let postBody = updateEquipeDto;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling updateTeamA");
      }
      // verify the required parameter 'updateEquipeDto' is set
      if (updateEquipeDto === undefined || updateEquipeDto === null) {
        throw new Error("Missing the required parameter 'updateEquipeDto' when calling updateTeamA");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['sport_auth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = EquipeDto;
      return this.apiClient.callApi(
        '/Equipe/{id}', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * update une équipe existante
     * update une équipe existante
     * @param {Number} id The id that needs to be deleted
     * @param {module:model/UpdateEquipeDto} updateEquipeDto update an new Team
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/EquipeDto}
     */
    updateTeamA(id, updateEquipeDto) {
      return this.updateTeamAWithHttpInfo(id, updateEquipeDto)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
