/**
 * Swagger SportApplicatioh - OpenAPI 3.0
 * This is a sample Pet Store Server based on the OpenAPI 3.0 specification. You can find out more about Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach! You can now help us improve the API whether it's by making changes to the definition itself or to the code. That way, with time, we can improve the API in general, and expose some of the new features in OAS3.  _If you're looking for the Swagger 2.0/OAS 2.0 version of Petstore, then click [here](https://editor.swagger.io/?url=https://petstore.swagger.io/v2/swagger.yaml). Alternatively, you can load via the `Edit > Load Petstore OAS 2.0` menu option!_  Some useful links: - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore) - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
 *
 * The version of the OpenAPI document: 1.0.11
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CreateStatistiqueMatchDto from '../model/CreateStatistiqueMatchDto';
import StatistiqueMatchDto from '../model/StatistiqueMatchDto';

/**
* StatMatch service.
* @module api/StatMatchApi
* @version 1.0.11
*/
export default class StatMatchApi {

    /**
    * Constructs a new StatMatchApi. 
    * @alias module:api/StatMatchApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * crée un nouveau StatMatch
     * crée un nouveau StatMatch
     * @param {module:model/CreateStatistiqueMatchDto} createStatistiqueMatchDto Create an new StatMatch
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/StatistiqueMatchDto} and HTTP response
     */
    createStatMatchWithHttpInfo(createStatistiqueMatchDto) {
      let postBody = createStatistiqueMatchDto;
      // verify the required parameter 'createStatistiqueMatchDto' is set
      if (createStatistiqueMatchDto === undefined || createStatistiqueMatchDto === null) {
        throw new Error("Missing the required parameter 'createStatistiqueMatchDto' when calling createStatMatch");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = StatistiqueMatchDto;
      return this.apiClient.callApi(
        '/StatMatch', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * crée un nouveau StatMatch
     * crée un nouveau StatMatch
     * @param {module:model/CreateStatistiqueMatchDto} createStatistiqueMatchDto Create an new StatMatch
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/StatistiqueMatchDto}
     */
    createStatMatch(createStatistiqueMatchDto) {
      return this.createStatMatchWithHttpInfo(createStatistiqueMatchDto)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * récupérer tous les StatMatch par matchId
     * @param {String} matchId The MacthId of the StatMatch to retrieve
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/StatistiqueMatchDto>} and HTTP response
     */
    getStatMatchByMatchIdWithHttpInfo(matchId) {
      let postBody = null;
      // verify the required parameter 'matchId' is set
      if (matchId === undefined || matchId === null) {
        throw new Error("Missing the required parameter 'matchId' when calling getStatMatchByMatchId");
      }

      let pathParams = {
        'MatchId': matchId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [StatistiqueMatchDto];
      return this.apiClient.callApi(
        '/StatMatch/{MatchId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * récupérer tous les StatMatch par matchId
     * @param {String} matchId The MacthId of the StatMatch to retrieve
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/StatistiqueMatchDto>}
     */
    getStatMatchByMatchId(matchId) {
      return this.getStatMatchByMatchIdWithHttpInfo(matchId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
