/**
 * Swagger SportApplicatioh - OpenAPI 3.0
 * This is a sample Pet Store Server based on the OpenAPI 3.0 specification. You can find out more about Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach! You can now help us improve the API whether it's by making changes to the definition itself or to the code. That way, with time, we can improve the API in general, and expose some of the new features in OAS3.  _If you're looking for the Swagger 2.0/OAS 2.0 version of Petstore, then click [here](https://editor.swagger.io/?url=https://petstore.swagger.io/v2/swagger.yaml). Alternatively, you can load via the `Edit > Load Petstore OAS 2.0` menu option!_  Some useful links: - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore) - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
 *
 * The version of the OpenAPI document: 1.0.11
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CreateTournoiDto from '../model/CreateTournoiDto';
import TournoiDto from '../model/TournoiDto';

/**
* Tournoi service.
* @module api/TournoiApi
* @version 1.0.11
*/
export default class TournoiApi {

    /**
    * Constructs a new TournoiApi. 
    * @alias module:api/TournoiApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * crée un nouveau tournoi
     * crée un nouveau tournoi
     * @param {module:model/CreateTournoiDto} createTournoiDto Create an new Tournament
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/TournoiDto} and HTTP response
     */
    createTournoiWithHttpInfo(createTournoiDto) {
      let postBody = createTournoiDto;
      // verify the required parameter 'createTournoiDto' is set
      if (createTournoiDto === undefined || createTournoiDto === null) {
        throw new Error("Missing the required parameter 'createTournoiDto' when calling createTournoi");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['sport_auth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TournoiDto;
      return this.apiClient.callApi(
        '/Tournoi', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * crée un nouveau tournoi
     * crée un nouveau tournoi
     * @param {module:model/CreateTournoiDto} createTournoiDto Create an new Tournament
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/TournoiDto}
     */
    createTournoi(createTournoiDto) {
      return this.createTournoiWithHttpInfo(createTournoiDto)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Récupérer toutes les tournois
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/TournoiDto>} and HTTP response
     */
    getAllTournoisWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['sport_auth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [TournoiDto];
      return this.apiClient.callApi(
        '/Tournoi', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Récupérer toutes les tournois
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/TournoiDto>}
     */
    getAllTournois() {
      return this.getAllTournoisWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * récupérer un tournoi par son id
     * @param {Number} id The id of the Tournoi to retrieve
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/TournoiDto} and HTTP response
     */
    getTournoiByIdWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getTournoiById");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['sport_auth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TournoiDto;
      return this.apiClient.callApi(
        '/Tournoi/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * récupérer un tournoi par son id
     * @param {Number} id The id of the Tournoi to retrieve
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/TournoiDto}
     */
    getTournoiById(id) {
      return this.getTournoiByIdWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * récupérer toutes les tournois par nom
     * @param {String} name The name of the Tournoi to retrieve
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/TournoiDto} and HTTP response
     */
    getTournoiByNameWithHttpInfo(name) {
      let postBody = null;
      // verify the required parameter 'name' is set
      if (name === undefined || name === null) {
        throw new Error("Missing the required parameter 'name' when calling getTournoiByName");
      }

      let pathParams = {
        'name': name
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['sport_auth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TournoiDto;
      return this.apiClient.callApi(
        '/Tournoi/name/{name}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * récupérer toutes les tournois par nom
     * @param {String} name The name of the Tournoi to retrieve
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/TournoiDto}
     */
    getTournoiByName(name) {
      return this.getTournoiByNameWithHttpInfo(name)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
