/**
 * Swagger SportApplicatioh - OpenAPI 3.0
 * This is a sample Pet Store Server based on the OpenAPI 3.0 specification. You can find out more about Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach! You can now help us improve the API whether it's by making changes to the definition itself or to the code. That way, with time, we can improve the API in general, and expose some of the new features in OAS3.  _If you're looking for the Swagger 2.0/OAS 2.0 version of Petstore, then click [here](https://editor.swagger.io/?url=https://petstore.swagger.io/v2/swagger.yaml). Alternatively, you can load via the `Edit > Load Petstore OAS 2.0` menu option!_  Some useful links: - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore) - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
 *
 * The version of the OpenAPI document: 1.0.11
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CreateUserDto from '../model/CreateUserDto';
import UserDto from '../model/UserDto';
import UserDtoRequest from '../model/UserDtoRequest';
import UserDtoResponse from '../model/UserDtoResponse';

/**
* User service.
* @module api/UserApi
* @version 1.0.11
*/
export default class UserApi {

    /**
    * Constructs a new UserApi. 
    * @alias module:api/UserApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * create user
     * @param {module:model/CreateUserDto} createUserDto 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/UserDto} and HTTP response
     */
    createUserWithHttpInfo(createUserDto) {
      let postBody = createUserDto;
      // verify the required parameter 'createUserDto' is set
      if (createUserDto === undefined || createUserDto === null) {
        throw new Error("Missing the required parameter 'createUserDto' when calling createUser");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = UserDto;
      return this.apiClient.callApi(
        '/user/create', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * create user
     * @param {module:model/CreateUserDto} createUserDto 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/UserDto}
     */
    createUser(createUserDto) {
      return this.createUserWithHttpInfo(createUserDto)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Logs user into the system
     * @param {module:model/UserDtoRequest} userDtoRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/UserDtoResponse} and HTTP response
     */
    loginUserWithHttpInfo(userDtoRequest) {
      let postBody = userDtoRequest;
      // verify the required parameter 'userDtoRequest' is set
      if (userDtoRequest === undefined || userDtoRequest === null) {
        throw new Error("Missing the required parameter 'userDtoRequest' when calling loginUser");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = UserDtoResponse;
      return this.apiClient.callApi(
        '/user/authenticate', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Logs user into the system
     * @param {module:model/UserDtoRequest} userDtoRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/UserDtoResponse}
     */
    loginUser(userDtoRequest) {
      return this.loginUserWithHttpInfo(userDtoRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Update user
     * This can only be done by the logged in user.
     * @param {Number} id ID du match à récupérer
     * @param {module:model/UserDto} userDto 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/UserDto} and HTTP response
     */
    updateUserWithHttpInfo(id, userDto) {
      let postBody = userDto;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling updateUser");
      }
      // verify the required parameter 'userDto' is set
      if (userDto === undefined || userDto === null) {
        throw new Error("Missing the required parameter 'userDto' when calling updateUser");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = UserDto;
      return this.apiClient.callApi(
        '/user/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Update user
     * This can only be done by the logged in user.
     * @param {Number} id ID du match à récupérer
     * @param {module:model/UserDto} userDto 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/UserDto}
     */
    updateUser(id, userDto) {
      return this.updateUserWithHttpInfo(id, userDto)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
