/**
 * Swagger SportApplicatioh - OpenAPI 3.0
 * This is a sample Pet Store Server based on the OpenAPI 3.0 specification. You can find out more about Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach! You can now help us improve the API whether it's by making changes to the definition itself or to the code. That way, with time, we can improve the API in general, and expose some of the new features in OAS3.  _If you're looking for the Swagger 2.0/OAS 2.0 version of Petstore, then click [here](https://editor.swagger.io/?url=https://petstore.swagger.io/v2/swagger.yaml). Alternatively, you can load via the `Edit > Load Petstore OAS 2.0` menu option!_  Some useful links: - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore) - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
 *
 * The version of the OpenAPI document: 1.0.11
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import StatistiqueMatchDto from './StatistiqueMatchDto';

/**
 * The MatchesUpdateDto model module.
 * @module model/MatchesUpdateDto
 * @version 1.0.11
 */
class MatchesUpdateDto {
    /**
     * Constructs a new <code>MatchesUpdateDto</code>.
     * @alias module:model/MatchesUpdateDto
     * @param score {String} Score du match
     * @param termine {Boolean} Indique si le match est terminé
     * @param isRevision {Boolean} 
     * @param dateRevision {Number} 
     */
    constructor(score, termine, isRevision, dateRevision) { 
        
        MatchesUpdateDto.initialize(this, score, termine, isRevision, dateRevision);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, score, termine, isRevision, dateRevision) { 
        obj['score'] = score;
        obj['termine'] = termine;
        obj['isRevision'] = isRevision;
        obj['dateRevision'] = dateRevision;
    }

    /**
     * Constructs a <code>MatchesUpdateDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MatchesUpdateDto} obj Optional instance to populate.
     * @return {module:model/MatchesUpdateDto} The populated <code>MatchesUpdateDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MatchesUpdateDto();

            if (data.hasOwnProperty('score')) {
                obj['score'] = ApiClient.convertToType(data['score'], 'String');
            }
            if (data.hasOwnProperty('termine')) {
                obj['termine'] = ApiClient.convertToType(data['termine'], 'Boolean');
            }
            if (data.hasOwnProperty('isRevision')) {
                obj['isRevision'] = ApiClient.convertToType(data['isRevision'], 'Boolean');
            }
            if (data.hasOwnProperty('dateRevision')) {
                obj['dateRevision'] = ApiClient.convertToType(data['dateRevision'], 'Number');
            }
            if (data.hasOwnProperty('stats')) {
                obj['stats'] = ApiClient.convertToType(data['stats'], [StatistiqueMatchDto]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MatchesUpdateDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MatchesUpdateDto</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of MatchesUpdateDto.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['score'] && !(typeof data['score'] === 'string' || data['score'] instanceof String)) {
            throw new Error("Expected the field `score` to be a primitive type in the JSON string but got " + data['score']);
        }
        if (data['stats']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['stats'])) {
                throw new Error("Expected the field `stats` to be an array in the JSON data but got " + data['stats']);
            }
            // validate the optional field `stats` (array)
            for (const item of data['stats']) {
                StatistiqueMatchDto.validateJsonObject(item);
            };
        }

        return true;
    }

/**
     * Returns Score du match
     * @return {String}
     */
    getScore() {
        return this.score;
    }

    /**
     * Sets Score du match
     * @param {String} score Score du match
     */
    setScore(score) {
        this['score'] = score;
    }
/**
     * Returns Indique si le match est terminé
     * @return {Boolean}
     */
    getTermine() {
        return this.termine;
    }

    /**
     * Sets Indique si le match est terminé
     * @param {Boolean} termine Indique si le match est terminé
     */
    setTermine(termine) {
        this['termine'] = termine;
    }
/**
     * @return {Boolean}
     */
    getIsRevision() {
        return this.isRevision;
    }

    /**
     * @param {Boolean} isRevision
     */
    setIsRevision(isRevision) {
        this['isRevision'] = isRevision;
    }
/**
     * @return {Number}
     */
    getDateRevision() {
        return this.dateRevision;
    }

    /**
     * @param {Number} dateRevision
     */
    setDateRevision(dateRevision) {
        this['dateRevision'] = dateRevision;
    }
/**
     * @return {Array.<module:model/StatistiqueMatchDto>}
     */
    getStats() {
        return this.stats;
    }

    /**
     * @param {Array.<module:model/StatistiqueMatchDto>} stats
     */
    setStats(stats) {
        this['stats'] = stats;
    }

}

MatchesUpdateDto.RequiredProperties = ["score", "termine", "isRevision", "dateRevision"];

/**
 * Score du match
 * @member {String} score
 */
MatchesUpdateDto.prototype['score'] = undefined;

/**
 * Indique si le match est terminé
 * @member {Boolean} termine
 */
MatchesUpdateDto.prototype['termine'] = undefined;

/**
 * @member {Boolean} isRevision
 */
MatchesUpdateDto.prototype['isRevision'] = undefined;

/**
 * @member {Number} dateRevision
 */
MatchesUpdateDto.prototype['dateRevision'] = undefined;

/**
 * @member {Array.<module:model/StatistiqueMatchDto>} stats
 */
MatchesUpdateDto.prototype['stats'] = undefined;






export default MatchesUpdateDto;

