/**
 * Swagger SportApplicatioh - OpenAPI 3.0
 * This is a sample Pet Store Server based on the OpenAPI 3.0 specification. You can find out more about Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach! You can now help us improve the API whether it's by making changes to the definition itself or to the code. That way, with time, we can improve the API in general, and expose some of the new features in OAS3.  _If you're looking for the Swagger 2.0/OAS 2.0 version of Petstore, then click [here](https://editor.swagger.io/?url=https://petstore.swagger.io/v2/swagger.yaml). Alternatively, you can load via the `Edit > Load Petstore OAS 2.0` menu option!_  Some useful links: - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore) - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
 *
 * The version of the OpenAPI document: 1.0.11
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MatchesDto from './MatchesDto';

/**
 * The TournoiDto model module.
 * @module model/TournoiDto
 * @version 1.0.11
 */
class TournoiDto {
    /**
     * Constructs a new <code>TournoiDto</code>.
     * @alias module:model/TournoiDto
     */
    constructor() { 
        
        TournoiDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TournoiDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TournoiDto} obj Optional instance to populate.
     * @return {module:model/TournoiDto} The populated <code>TournoiDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TournoiDto();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('match')) {
                obj['match'] = ApiClient.convertToType(data['match'], [MatchesDto]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TournoiDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TournoiDto</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        if (data['match']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['match'])) {
                throw new Error("Expected the field `match` to be an array in the JSON data but got " + data['match']);
            }
            // validate the optional field `match` (array)
            for (const item of data['match']) {
                MatchesDto.validateJsonObject(item);
            };
        }

        return true;
    }

/**
     * Returns identifiant of the tournoi
     * @return {Number}
     */
    getId() {
        return this.id;
    }

    /**
     * Sets identifiant of the tournoi
     * @param {Number} id identifiant of the tournoi
     */
    setId(id) {
        this['id'] = id;
    }
/**
     * Returns name of tournoi
     * @return {String}
     */
    getName() {
        return this.name;
    }

    /**
     * Sets name of tournoi
     * @param {String} name name of tournoi
     */
    setName(name) {
        this['name'] = name;
    }
/**
     * @return {Array.<module:model/MatchesDto>}
     */
    getMatch() {
        return this.match;
    }

    /**
     * @param {Array.<module:model/MatchesDto>} match
     */
    setMatch(match) {
        this['match'] = match;
    }

}



/**
 * identifiant of the tournoi
 * @member {Number} id
 */
TournoiDto.prototype['id'] = undefined;

/**
 * name of tournoi
 * @member {String} name
 */
TournoiDto.prototype['name'] = undefined;

/**
 * @member {Array.<module:model/MatchesDto>} match
 */
TournoiDto.prototype['match'] = undefined;






export default TournoiDto;

