/**
 * Swagger SportApplicatioh - OpenAPI 3.0
 * This is a sample Pet Store Server based on the OpenAPI 3.0 specification. You can find out more about Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach! You can now help us improve the API whether it's by making changes to the definition itself or to the code. That way, with time, we can improve the API in general, and expose some of the new features in OAS3.  _If you're looking for the Swagger 2.0/OAS 2.0 version of Petstore, then click [here](https://editor.swagger.io/?url=https://petstore.swagger.io/v2/swagger.yaml). Alternatively, you can load via the `Edit > Load Petstore OAS 2.0` menu option!_  Some useful links: - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore) - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
 *
 * The version of the OpenAPI document: 1.0.11
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import JoueurDto from './JoueurDto';

/**
 * The UpdateEquipeAdverseDto model module.
 * @module model/UpdateEquipeAdverseDto
 * @version 1.0.11
 */
class UpdateEquipeAdverseDto {
    /**
     * Constructs a new <code>UpdateEquipeAdverseDto</code>.
     * @alias module:model/UpdateEquipeAdverseDto
     */
    constructor() { 
        
        UpdateEquipeAdverseDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateEquipeAdverseDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateEquipeAdverseDto} obj Optional instance to populate.
     * @return {module:model/UpdateEquipeAdverseDto} The populated <code>UpdateEquipeAdverseDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateEquipeAdverseDto();

            if (data.hasOwnProperty('Joueur')) {
                obj['Joueur'] = ApiClient.convertToType(data['Joueur'], [JoueurDto]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateEquipeAdverseDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateEquipeAdverseDto</code>.
     */
    static validateJSON(data) {
        if (data['Joueur']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['Joueur'])) {
                throw new Error("Expected the field `Joueur` to be an array in the JSON data but got " + data['Joueur']);
            }
            // validate the optional field `Joueur` (array)
            for (const item of data['Joueur']) {
                JoueurDto.validateJsonObject(item);
            };
        }

        return true;
    }

/**
     * @return {Array.<module:model/JoueurDto>}
     */
    getJoueur() {
        return this.Joueur;
    }

    /**
     * @param {Array.<module:model/JoueurDto>} joueur
     */
    setJoueur(joueur) {
        this['Joueur'] = joueur;
    }

}



/**
 * @member {Array.<module:model/JoueurDto>} Joueur
 */
UpdateEquipeAdverseDto.prototype['Joueur'] = undefined;






export default UpdateEquipeAdverseDto;

